name: syp_state_manager
description: "Simple Yet Powerful State Manager for Flutter"
version: 0.0.1
publish_to: "https://pub.dev"
homepage: https://github.com/syedadeel2/syp_state_manager

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
